name: Deploy to App Service

on:
  workflow_call:
    inputs:
      appServiceName:
        description: The name of the App Service
        required: true
        type: string
      slot:
        description: The slot to deploy the application to
        default: production
        required: false
        type: string
      ref:
        description: The branch, tag or commit (SHA) to deploy
        default: main
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ApsSlotsDemo.App

    permissions:
      id-token: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: dotnet publish
        run: dotnet publish -c Release -o publish/ApsSlotsDemo.App

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ inputs.appServiceName }} 
          slot-name: ${{ inputs.slot }}
          package: ./src/ApsSlotsDemo.App/publish/ApsSlotsDemo.App
