name: 02 - Swap App Service slots using Azure CLI

on:
  workflow_dispatch:

jobs:
  swap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Swap WebApp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp deployment slot swap -g ${{ secrets.RG_NAME }} -n ${{ secrets.APP_NAME }} -s staging
      
      - name: Determine new version of the app
        id: choose-version
        uses: azure/CLI@v1
        with:
          inlineScript: |
            previousVersion=$(az deployment sub show -n apsBicepDemo --query properties.parameters.activeApp.value -o tsv 2>/dev/null)
            [[ "$previousVersion" == 'green' ]] && versionToUse="blue" || versionToUse="green"
            echo "appVersion=$versionToUse" >> $GITHUB_OUTPUT
      
      - name: Bicep deploy
        id: bicep-deploy
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: ${{ secrets.AZURE_REGION }}
          template: ./infra/main.bicep
          parameters: project=bicep-aps-demo location=${{ secrets.AZURE_REGION }} activeApp=${{ steps.choose-version.outputs.appVersion }}
          deploymentName: apsBicepDemo
