name: 03 - Destroy Azure resources with Azure CLI

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: infra

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Delete resource group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group delete -g ${{ vars.RG_NAME }} -y
