name: 02 - Swap App Service slots using Azure CLI

on:
  workflow_dispatch:

jobs:
  swap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Swap WebApp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp deployment slot swap -g ${{ secrets.RG_NAME }} -n ${{ secrets.APP_NAME }} -s staging
      
      - name: Determine new version of the app
        id: choose-version
        uses: azure/CLI@v1
        with:
          inlineScript: |
            previousVersion=$(az deployment group show -g ${{ secrets.RG_NAME }} -n deploy-bicep-aps-demo-resources --query properties.parameters.activeApp.value -o tsv 2>/dev/null)
            [[ "$previousVersion" == 'green' ]] && versionToUse="blue" || versionToUse="green"
            echo "appVersion=$versionToUse" >> $GITHUB_OUTPUT
  
  update-active-app:
    uses: ./.github/workflows/bicep-deploy.yml
    with:
      activeApp: ${{ steps.choose-version.outputs.appVersion }}
      updateSecrets: false
    secrets: inherit
