name: Provision Azure resources with Bicep

on:
  workflow_call:
    outputs:
      appServiceName:
        description: The name of the App Service
        value: ${{ jobs.provision.outputs.appServiceName }}

defaults:
  run:
    working-directory: infra

jobs:
  provision:
    runs-on: ubuntu-latest

    outputs:
      appServiceName: ${{ steps.bicep-deploy.outputs.appServiceName }}

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # - name: Determine the version of the app
      #   id: choose-version
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       previousVersion=$(az deployment group show -g ${{ secrets.RG_NAME }} -n deploy-bicep-aps-demo-resources --query properties.parameters.activeApp.value -o tsv 2>/dev/null)
      #       [[ "$previousVersion" == 'green' ]] && versionToUse="green" || versionToUse="blue"
      #       echo "appVersion=$versionToUse" >> $GITHUB_OUTPUT
      
      - name: Bicep deploy
        id: bicep-deploy
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: ${{ secrets.AZURE_REGION }}
          template: ./infra/main.bicep
          parameters: project=bicep-aps-demo location=${{ secrets.AZURE_REGION }}
          # parameters: project=bicep-aps-demo location=${{ secrets.AZURE_REGION }} activeApp=${{ steps.choose-version.outputs.appVersion }}
          deploymentName: apsBicepDemo

      - name: Update GitHub secrets
        run: |
          gh secret set RG_NAME --body ${{ steps.bicep-deploy.outputs.rgName }}
          gh secret set APP_NAME --body ${{ steps.bicep-deploy.outputs.appServiceName }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
